[package]
edition = "2018"
build = "./common/build/build.rs"
name = "adnl"
version = "0.1.19"
description = "ADNL library"

[dependencies]
aes-ctr = "0.6.0"
arrayref = "0.3.5"
async-trait = "0.1.22"
base64 = "0.11.0"
curve25519-dalek = "2.0.0"
ed25519 = "1.0.1"
ed25519-dalek = "1.0.0-pre.4"
external-ip = { version = "4.1.0", optional = true }
failure = "0.1.6"
futures = "0.3.1"
log = "0.4.11"
rand = "0.7.2"
serde = { version = "1.0.105", features = ["derive", "rc"] }
serde_json = "1.0.41"
sha2 = "0.8.0"
socket2 = "0.3.19"
stream-cancel = "0.8.0"
tokio = { version = "1.3.0", features = ["io-util", "net", "rt-multi-thread"] }
tokio-io-timeout = "1.1.1"
tokio-stream = { version = "0.1.4", features = ["net"] }
x25519-dalek = "0.6.0"

ton_api = { git = "https://github.com/tonlabs/ton-labs-tl.git", package = "ton_api" }
ton_types = { git = "https://github.com/tonlabs/ton-labs-types.git" }
lockfree = { git = "https://github.com/tonlabs/lockfree.git" }

[dev-dependencies]
external-ip = "4.1.0"         
hex = "^0"
log4rs = "0.8.3"

[features]
client = []
server = []
node = ["external-ip"]
telemetry = []

