[package]
build = './common/build/build.rs'
description = 'ADNL library'
edition = '2018'
name = 'adnl'
version = '0.7.65'

[workspace]


[dependencies]
aes-ctr = '0.6.0'
async-trait = '0.1.22'
base64 = '0.13'
curve25519-dalek = '3.2'
ed25519 = '1.0'
ed25519-dalek = '1.0'
failure = '0.1.6'
futures = '0.3.1'
log = '0.4'
num_cpus = '1.13'
rand = '0.7'
serde_json = '1.0.41'
sha2 = '0.9'
socket2 = '0.3.19'
stream-cancel = '0.8.0'
tokio-io-timeout = '1.1.1'
x25519-dalek = '1.2'
external-ip = { optional = true, version = '4.1.0' }
lockfree = { git = 'https://github.com/tonlabs/lockfree.git' }
serde = { features = [ 'derive', 'rc' ], version = '1.0.105' }
tokio = { features = [ 'io-util', 'macros', 'net', 'rt-multi-thread' ], version = '1.5.0' }
tokio-stream = { features = [ 'net' ], version = '0.1.4' }
ton_api = { git = 'https://github.com/tonlabs/ton-labs-tl', package = 'ton_api', tag = '0.2.120' }
ton_types = { git = 'https://github.com/tonlabs/ton-labs-types', tag = '1.10.12' }
zstd = { features = [ 'pkg-config' ], optional = true, version = '0.8' }

[dev-dependencies]
external-ip = '4.1'
hex = '0.4'
log4rs = '1.0'

[features]
client = [  ]
compression = [ 'zstd' ]
default = [ 'static_workers' ]
node = [ 'external-ip' ]
server = [  ]
static_workers = [  ]
telemetry = [  ]

